# Generated by Django 4.2.9 on 2026-04-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('ministry', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('agriculture', 'Agriculture'), ('education', 'Education'), ('housing', 'Housing'), ('health', 'Health'), ('women', 'Women & Child'), ('employment', 'Employment'), ('social', 'Social Security'), ('finance', 'Finance & Loans')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('official_url', models.URLField(blank=True, null=True)),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('eligible_category', models.CharField(choices=[('all', 'All Categories'), ('sc', 'SC Only'), ('st', 'ST Only'), ('obc', 'OBC Only'), ('sc_st', 'SC + ST'), ('sc_st_obc', 'SC + ST + OBC'), ('general', 'General Only')], db_index=True, default='all', max_length=20)),
                ('eligible_occupation', models.CharField(choices=[('all', 'All Occupations'), ('farmer', 'Farmer'), ('labour', 'Labour'), ('student', 'Student'), ('self_employed', 'Self-Employed'), ('business', 'Business'), ('teacher', 'Teacher'), ('other', 'Other')], default='all', max_length=30)),
                ('eligible_gender', models.CharField(choices=[('all', 'All Genders'), ('male', 'Male Only'), ('female', 'Female Only')], default='all', max_length=10)),
                ('eligible_state', models.CharField(default='all', max_length=50)),
                ('min_income', models.PositiveIntegerField(default=0)),
                ('max_income', models.PositiveIntegerField(blank=True, null=True)),
                ('benefit_amount', models.PositiveIntegerField()),
                ('benefit_period', models.CharField(choices=[('per_year', 'Per Year'), ('per_month', 'Per Month'), ('one_time', 'One-time'), ('per_installment', 'Per Installment')], default='per_year', max_length=20)),
                ('required_documents', models.TextField(blank=True, default='')),
                ('last_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
            ],
            options={
                'db_table': 'schemes',
                'ordering': ['last_date'],
            },
        ),
    ]
