# Generated by Django 4.2.9 on 2026-04-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC')], default='general', max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('income_range', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('labour', 'Labour'), ('self_employed', 'Self-Employed'), ('business', 'Business'), ('teacher', 'Teacher'), ('student', 'Student'), ('govt_employee', 'Govt Employee'), ('private_employee', 'Private Employee'), ('other', 'Other')], max_length=30, null=True)),
                ('state', models.CharField(blank=True, choices=[('andhra_pradesh', 'Andhra Pradesh'), ('telangana', 'Telangana'), ('tamil_nadu', 'Tamil Nadu'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('maharashtra', 'Maharashtra'), ('gujarat', 'Gujarat'), ('rajasthan', 'Rajasthan'), ('madhya_pradesh', 'Madhya Pradesh'), ('uttar_pradesh', 'Uttar Pradesh'), ('bihar', 'Bihar'), ('west_bengal', 'West Bengal'), ('other', 'Other')], max_length=30, null=True)),
                ('has_land', models.CharField(choices=[('no', 'No'), ('yes_less_2ha', 'Yes < 2ha'), ('yes_more_2ha', 'Yes > 2ha')], default='no', max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('family_size', models.PositiveSmallIntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Profile',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSchemeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.IntegerField()),
                ('applied', models.BooleanField(default=False)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_scheme_status',
                'unique_together': {('user', 'scheme_id')},
            },
        ),
    ]
