# Generated by Django 4.2.9 on 2026-04-08 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschemestatus',
            name='scheme_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_statuses', to='schemes.scheme'),
        ),
        migrations.RenameField(
            model_name='userschemestatus',
            old_name='scheme_id',
            new_name='scheme',
        ),
    ]
