# Generated by Django 4.2.9 on 2026-04-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('schemes_created', models.PositiveIntegerField(default=0)),
                ('schemes_skipped', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_log', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'upload_history',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
